app/main/forms.py
#! -*-coding:utf-8-*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo


class PeixunApplyForm(FlaskForm):
    username = StringField(id='username', validators=[DataRequired()])
    phone = StringField(id='', validators=[DataRequired()])
    card_num = StringField(id='', validators=[DataRequired()])
    address = StringField(id='', validators=[DataRequired()])
    date = StringField(id='', validators=[DataRequired()])
    reason = StringField(id='', validators=[DataRequired()])
    content = StringField(id='', validators=[DataRequired()])


class PatentApplyForm(FlaskForm):
    name = StringField(id='', validators=[DataRequired()])
    type = StringField(id='', validators=[DataRequired()])
    main_per_name = StringField(id='', validators=[DataRequired()])
    first_per_name = StringField(id='', validators=[DataRequired()])
    first_per_phone = StringField(id='', validators=[DataRequired()])
    first_per_card_num = StringField(id='', validators=[DataRequired()])
    first_per_address= StringField(id='', validators=[DataRequired()])
    date = StringField(id='', validators=[DataRequired()])
    priority = StringField(id='', validators=[DataRequired()])
    description = StringField(id='', validators=[DataRequired()])


class FeeApplyForm(FlaskForm):
    patent_id = StringField(id='', validators=[DataRequired()])
    name = StringField(id='', validators=[DataRequired()])
    phone = StringField(id='', validators=[DataRequired()])
    date = StringField(id='', validators=[DataRequired()])
    description = StringField(id='', validators=[DataRequired()])


class TradeApplyForm(FlaskForm):
    username = StringField(id='', validators=[DataRequired()])
    phone = StringField(id='', validators=[DataRequired()])
    date = StringField(id='', validators=[DataRequired()])
    patent_id = StringField(id='', validators=[DataRequired()])


class TradePerchaseForm(FlaskForm):
    username = StringField(id='', validators=[DataRequired()])
    phone = StringField(id='', validators=[DataRequired()])
    date = StringField(id='', validators=[DataRequired()])
    patent_id = StringField(id='', validators=[DataRequired()])

app/main/__init__.py
#! -*- coding:utf-8 -*-
from flask import Blueprint

main = Blueprint('main',__name__)

import views
import errors

app/main/views.py
#! -*-coding:utf-8 -*-
from flask import render_template, redirect, url_for, request, session,flash
from flask_login import login_user, logout_user, login_required, current_user

from . import main
from .forms import PeixunApplyForm,PatentApplyForm,FeeApplyForm,TradeApplyForm,TradePerchaseForm
from ..models import *


def check_jihuo_status(mail_address):
    com_obj = CompanyRegisterModel.query.filter_by(mail_address=mail_address).first()
    per_obj = PersonRegisterModel.query.filter_by(mail_address=mail_address).first()
    if com_obj:
        if com_obj.register_status == 1:
            return True
        else:
            return False
    if per_obj:
        if per_obj.register_status == 1:
            return True
        else:
            return False
    return False


def check_user_type(mail_address):
    if check_jihuo_status(session['username']):
        com_obj = CompanyInfoModel.query.filter_by(mail_address=mail_address).first()
        per_obj = PersonInfoModel.query.filter_by(mail_address=mail_address).first()
    else:
        com_obj = CompanyRegisterModel.query.filter_by(mail_address=mail_address).first()
        per_obj = PersonRegisterModel.query.filter_by(mail_address=mail_address).first()
    if com_obj:
        return 'company'
    elif per_obj:
        return 'person'
    else:
        return 'person'


@main.route('/main/user_center.html',methods=['GET'])
@login_required
def user_center():
    return render_template('houtai/main.html')


@main.route('/main', methods=['GET'])
@login_required
def main_handler():
    return render_template('houtai/main.html')


@main.route('/main/left.html', methods=['GET'])
@login_required
def left():
    return render_template('houtai/left.html')


@main.route('/main/blank.html', methods=['GET'])
@login_required
def blank():
    return render_template('houtai/blank.html')


@main.route('/main/head.html', methods=['GET'])
@login_required
def head():
    username = session['username']
    return render_template('houtai/head.html', username=username)


@main.route('/main/patent_apply.html', methods=['GET', 'POST'])
@login_required
def patent_apply():
    form = PatentApplyForm()
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    if request.method == 'POST':
        account_username = session['username']
        account_type = check_jihuo_status(account_username)
        name = form.name.data
        type = form.type.data
        main_per_name = form.main_per_name.data
        first_per_name = form.first_per_name.data
        first_per_phone = form.first_per_phone.data
        first_per_card_num = form.first_per_card_num.data
        first_per_address = form.first_per_address.data
        date = form.date.data
        priority = form.priority.data
        description = form.description.data
        check_status = 'checking'
        obj = PatentApplyModel(account_username=account_username,account_type=account_type,
                               name=name,type=type,main_per_name=main_per_name,
                               first_per_name=first_per_name,first_per_address=first_per_address,
                               first_per_phone=first_per_phone,first_per_card_num=first_per_card_num,
                               date=date,priority=priority,description=description,
                               check_status=check_status)
        db.session.add(obj)
        db.session.commit()
        flash('提交成功')
    return render_template('houtai/patent_apply.html', form=form)


@main.route('/main/patent_record.html', methods=['GET'])
@login_required
def patent_record():
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    obj = PatentApplyModel.query.filter_by(account_username=session['username']).all()
    return render_template('houtai/patent_record.html', info=obj)


@main.route('/main/peixun_record.html', methods=['GET'])
@login_required
def peixun_record():
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    obj = PeixunApplyModel.query.filter_by(account_username=session['username']).all()
    return render_template('houtai/peixun_record.html', info=obj)


@main.route('/main/peixun_apply.html', methods=['GET', 'POST'])
@login_required
def peixun_apply():
    form = PeixunApplyForm()
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    if request.method == 'POST':
        if form.validate_on_submit():
            account_username = session['username']
            user_type = check_user_type(session['username'])
            username = form.username.data
            phone = form.phone.data
            card_num = form.card_num.data
            address =form.address.data
            date = form.date.data
            reason = form.reason.data
            content = form.content.data
            obj = PeixunApplyModel(account_username=account_username, account_type=user_type, username=username, phone=phone,
                                   card_num=card_num, address=address, date=date, reason=reason,content=content)
            db.session.add(obj)
            db.session.commit()
            flash('提交成功')
            return render_template('houtai/peixun_apply.html', form=form)
    return render_template('houtai/peixun_apply.html', form=form)


@main.route('/main/fee_apply.html', methods=['GET','POST'])
@login_required
def fee_apply():
    form = FeeApplyForm()
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    # get the patent id
    patent_id_obj = PatentApplyModel.query.filter_by(account_username=session['username'],check_status='2checked').all()
    if request.method == 'POST':
        if form.validate_on_submit():
            account_username = session['username']
            user_type = check_user_type(session['username'])
            patent_id = form.patent_id.data
            name = form.name.data
            phone = form.phone.data
            date = form.date.data
            description = form.description.data
            obj = FeeApplyModel(account_username=account_username,account_type=user_type,patent_id=patent_id,
                                name=name,phone=phone,date=date,description=description)
            db.session.add(obj)
            db.session.commit()
            flash('提交成功')
            return render_template('houtai/fee_apply.html', form=form, info=patent_id_obj)
        else:
            flash('提交失败，请查看专利号是否已经审查')
    return render_template('houtai/fee_apply.html', form=form, info=patent_id_obj)


@main.route('/main/fee_record.html', methods=['GET'])
@login_required
def fee_record():
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    obj = FeeApplyModel.query.filter_by(account_username=session['username']).all()
    return render_template('houtai/fee_record.html', info=obj)


@main.route('/main/trade_apply.html', methods=['GET', 'POST'])
@login_required
def trade_apply():
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    form = TradeApplyForm()
    # get my own patent id in order to trade
    obj = PatentApplyModel.query.filter_by(account_username=session['username'],check_status='2checked').all()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            phone = form.phone.data
            date = form.date.data
            patent_id = form.patent_id.data
            obj1 = PatentApplyModel.query.filter_by(id=patent_id,check_status='2checked',account_username=session['username']).first()
            if not obj1:
                flash('交易专利号不合法，请检查专利号是否存在或通过审查')
                flash('请重新提交')
                render_template('houtai/trade_apply.html', form=form)
            else:
                tmp = PatentApplyModel.query.filter_by(id=patent_id).first()
                description = tmp.description
                obj2 = TradeApplyModel(apply_per_name=username,patent_id=patent_id,apply_per_phone=phone,date=date,apply_description=description)
                db.session.add(obj2)
                db.session.commit()
                flash('提交成功')
                render_template('houtai/trade_apply.html', form=form, info=obj)
    return render_template('houtai/trade_apply.html',form=form, info=obj)


@main.route('/main/trade_perchase.html', methods=['GET', 'POST'])
@login_required
def trade_perchase():
    if check_jihuo_status(session['username']) == False:
        flash('请等待管理员认证')
        return render_template('houtai/blank.html')
    form = TradePerchaseForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            username = form.username.data
            phone = form.phone.data
            date = form.date.data
            patent_id = form.patent_id.data
            obj1 = TradeApplyModel.query.filter_by(id=patent_id,check_status='checked').first()
            if not obj1:
                flash('交易专利号不合法，请检查专利号是否存在或通过审查')
                flash('请重新提交')
                render_template('houtai/trade_perchase.html', form=form)
            else:
                obj2 = TradePerchaseModel(perchase_per_name=username,patent_id=patent_id,date=date,perchase_per_phone=phone)
                db.session.add(obj2)
                db.session.commit()

app/templates/houtai/fee_apply.html
{% extends 'houtai/base2.html' %}
{% block body %}
    <body>

<section id="getintouch" class="rotateInUpLeft animated">
<div class="container">
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
  <legend>专利相关费用申请</legend>
</fieldset>

<form class="layui-form" action="{{ url_for('main.fee_apply') }}" id="form" method="post">
    {{ form.csrf_token }}
  <div class="layui-form-item">
    <label class="layui-form-label">选择专利号</label>
    <div class="layui-input-block">
        <select name="patent_id" lay-verfiy="required" lay-search="">
            <option value="">选择或搜索</option>
            {% if info %}
                {% for i in info %}
                    <option value="{{ i.id }}">{{ i.name }}</option>
                {% endfor %}
            {% endif %}
        </select>
    </div>
  </div>
    {{ form.csrf_token }}
  <div class="layui-form-item">
    <label class="layui-form-label">费用申请人姓名</label>
    <div class="layui-input-block">
      <input type="text" name="name" lay-verify="title" autocomplete="off" placeholder="请输入名称" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">申请人手机号</label>
    <div class="layui-input-block">
      <input type="text" name="phone" lay-verify="title" autocomplete="off" placeholder="请输入名称" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">申请日期</label>
      <div class="layui-input-inline">
        <input type="text" name="date" id="date" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
      </div>
    </div>
  </div>
  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">费用用途描述</label>
    <div class="layui-input-block">
      <textarea name="description" placeholder="请输入内容" class="layui-textarea"></textarea>
    </div>
  </div>
  <!--<div class="layui-form-item layui-form-text">
    <label class="layui-form-label">编辑器</label>
    <div class="layui-input-block">
      <textarea class="layui-textarea layui-hide" name="content" lay-verify="content" id="LAY_demo_editor"></textarea>
    </div>
  </div>-->
  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn" lay-submit="" lay-filter="demo1" type="submit">立即提交</button>
      <button type="reset" class="layui-btn layui-btn-primary">重置</button>
    </div>
  </div>
</form>
</div>
</section>
<script>
layui.use(['form', 'layedit', 'laydate'], function(){
  var form = layui.form
  ,layer = layui.layer
  ,layedit = layui.layedit
  ,laydate = layui.laydate;

  //日期
  laydate.render({
    elem: '#date'
  });
  laydate.render({
    elem: '#date1'
  });



});
</script>
</body>
{% endblock %}

app/templates/houtai/left.html
{% extends 'houtai/base.html' %}
{% block body %}
<body id="bg">
	<!-- 左边节点 -->
	<div class="container">

		<div class="leftsidebar_box">
			<a href="main.html" target="main"><div class="line">
					<img src="{{ url_for('static',filename='img/coin01.png') }}" />&nbsp;&nbsp;首页
				</div></a>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coin03.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coin04.png') }}" /> 用户信息<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.user_info') }}"
						target="main">个人信息</a><img class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coin01.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coin02.png') }}" /> 专利申请<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.patent_apply') }}"
						target="main">专利申请</a><img class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.patent_record') }}"
						target="main">申请记录</a><img class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coin07.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coin08.png') }}" /> 费用管理<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a href="{{ url_for('main.fee_apply') }}" target="main"
						class="cks">申请费用</a><img class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
                <dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a href="{{ url_for('main.fee_record') }}" target="main"
						class="cks">申请记录</a><img class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coin10.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coin09.png') }}" /> 专利交易<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.trade_market') }} " target="main">交易市场</a><img class="icon5"
						src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
                <dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.trade_apply') }} " target="main">发布交易</a><img class="icon5"
						src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>
			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coin11.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coin12.png') }}" /> 专利培训<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.peixun_apply') }} " target="main">培训申请</a><img
						class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
                <dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" href="{{ url_for('main.peixun_record') }}" target="main">培训记录</a><img
						class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>

			<dl class="system_log">
				<dt>
					<img class="icon1" src="{{ url_for('static',filename='img/coinL1.png') }}" /><img class="icon2"
						src="{{ url_for('static',filename='img/coinL2.png') }}" /> 系统管理<img class="icon3"
						src="{{ url_for('static',filename='img/coin19.png') }}" /><img class="icon4"
						src="{{ url_for('static',filename='img/coin20.png') }}" />
				</dt>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a href="{{ url_for('main.doing')}}"
						target="main" class="cks">修改密码</a><img class="icon5"
						src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
				<dd>
					<img class="coin11" src="{{ url_for('static',filename='img/coin111.png') }}" /><img class="coin22"
						src="{{ url_for('static',filename='img/coin222.png') }}" /><a class="cks" id='logout' href="javascript:top.location.href='{{ url_for('auth.logout') }}'">退出</a><img
						class="icon5" src="{{ url_for('static',filename='img/coin21.png') }}" />
				</dd>
			</dl>

		</div>

	</div>
<script>
    $.ready(function () {
        $('#logout').click(function () {
            href.location = "{{ url_for('auth.logout') }}";
        });
    });
</script>
</body>
{% endblock %}

app/templates/houtai/main.html
{% extends 'houtai/base.html' %}
{% block title %}个人用户专利控制台{% endblock %}
{% block body %}
<frameset rows="100,*" cols="*" scrolling="No" framespacing="0"
	frameborder="no" border="0"> <frame src="{{ url_for('main.head') }}"
	name="headmenu" id="mainFrame" title="mainFrame"><!-- 引用头部 -->
<!-- 引用左边和主体部分 --> <frameset rows="100*" cols="220,*" scrolling="No"
	framespacing="0" frameborder="no" border="0"> <frame
	src="{{ url_for('main.left') }}" name="leftmenu" id="mainFrame" title="mainFrame">
<frame src="{{ url_for('main.blank') }}" name="main" scrolling="yes" noresize="noresize"
	id="rightFrame" title="rightFrame"></frameset></frameset>
{% endblock %}

app/templates/houtai/patent_apply.html
{% extends 'houtai/base2.html' %}
{% block body %}
<body>

<section id="getintouch" class="rotateInUpLeft animated">
<div class="container">
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
  <legend>专利申请单</legend>
</fieldset>

<form class="layui-form" action="{{ url_for('main.patent_apply') }}" method="post">
  <div class="layui-form-item">
    <label class="layui-form-label">发明名称</label>
    <div class="layui-input-block">
      <input type="text" name="name" lay-verify="title" autocomplete="off" placeholder="请输入名称" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">专利类别</label>
    <div class="layui-input-block">
      <select name="type" lay-filter="aihao">
        <option value="computer">计算机</option>
        <option value="chemistry" selected="">生化</option>
        <option value="building">建筑学</option>
        <option value="machine">机械</option>
        <option value="protect">国防</option>
      </select>
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">发明人</label>
    <div class="layui-input-block">
      <input type="text" name="main_per_name" lay-verify="required" placeholder="请输入名字" autocomplete="off" class="layui-input">
    </div>
  </div>

  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">第一申请人姓名</label>
      <div class="layui-input-inline">
        <input type="tel" name="first_per_name"  autocomplete="off" class="layui-input">
      </div>
    </div>
    <div class="layui-inline">
      <label class="layui-form-label">第一申请人电话</label>
      <div class="layui-input-inline">
        <input type="text" name="first_per_phone"  autocomplete="off" class="layui-input">
      </div>
    </div>
    <div class="layui-inline">
      <label class="layui-form-label">第一申请人身份证</label>
      <div class="layui-input-inline">
        <input type="text" name="first_per_card_num"  autocomplete="off" class="layui-input">
      </div>
    </div>
  </div>
  <div class="layui-form-item">
    <label class="layui-form-label">第一申请人联系地址</label>
    <div class="layui-input-block">
      <input type="text" name="first_per_address"  autocomplete="off" placeholder="请输入名称" class="layui-input">
    </div>
  </div>
  <div class="layui-form-item">
    <div class="layui-inline">
      <label class="layui-form-label">申请日期</label>
      <div class="layui-input-inline">
        <input type="text" name="date" id="date" lay-verify="date" placeholder="yyyy-MM-dd" autocomplete="off" class="layui-input">
      </div>
    </div>
  </div>

  <div class="layui-form-item">
    <label class="layui-form-label">是否专利优先申请</label>
    <div class="layui-input-block">
      <input type="checkbox" name="priority" title="是">
    </div>
  </div>

  <div class="layui-form-item layui-form-text">
    <label class="layui-form-label">专利描述</label>
    <div class="layui-input-block">
      <textarea placeholder="请输入内容" name="description" class="layui-textarea"></textarea>
    </div>
  </div>

  <div class="layui-form-item layui-form-text">
      <!--
    <label class="layui-form-label">专利申请文档上传</label>
    <button type="button" class="layui-btn" id="test1">
      <i class="layui-icon">&#xe67c;</i>上传申请书
    </button>
    <button type="button" class="layui-btn" id="test1">
      <i class="layui-icon">&#xe601;</i>下载申请书样本
    </button>
    -->
    <script>
    layui.use('upload', function(){
      var upload = layui.upload;

      //执行实例
      var uploadInst = upload.render({
        elem: '#test1' //绑定元素
        ,url: '/upload/' //上传接口
        ,done: function(res){
          //上传完毕回调
        }
        ,error: function(){
          //请求异常回调
        }
      });
    });
    </script>

  </div>
  <!--<div class="layui-form-item layui-form-text">
    <label class="layui-form-label">编辑器</label>
    <div class="layui-input-block">
      <textarea class="layui-textarea layui-hide" name="content" lay-verify="content" id="LAY_demo_editor"></textarea>
    </div>
  </div>-->
  <div class="layui-form-item">
    <div class="layui-input-block">
      <button class="layui-btn" lay-submit="" lay-filter="demo1" type="submit">立即提交</button>
      <button type="reset" class="layui-btn layui-btn-primary">重置</button>
    </div>
  </div>
</form>
</div>
</section>

<script>
layui.use(['form', 'layedit', 'laydate'], function(){
  var form = layui.form
  ,layer = layui.layer
  ,layedit = layui.layedit
  ,laydate = layui.laydate;


  //监听指定开关
  form.on('switch(switchTest)', function(data){
    layer.msg('开关checked：'+ (this.checked ? 'true' : 'false'), {
      offset: '6px'
    });
    layer.tips('温馨提示：请注意开关状态的文字可以随意定义，而不仅仅是ON|OFF', data.othis)
  });

  //监听提交
  {#form.on('submit(demo1)', function(data){
    layer.alert(JSON.stringify(data.field), {
      title: '最终的提交信息'
    })
    return false;
  });#}


});
</script>
</body>
{% endblock %}

app/templates/houtai/trade_market.html
{% extends 'houtai/base2.html' %}
{% block body %}
    <body>
        <ul class="layui-timeline">
             {% if tradeinfo %}
                 {% for i in tradeinfo %}
                     <li class="layui-timeline-item">
                        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                        <div class="layui-timeline-content layui-text">
                          <h3 class="layui-timeline-title">{{ i.apply_date }}</h3>
                          <p>专利名：{{ i.patent_name }}</p>
                          <ul>
                            <li>申请人：{{ i.main_per_name }}</li>
                            <li>描述：{{ i.description }}</li>
                          </ul>
                            <a href="{{ url_for('main.trade_perchase') }}?id={{ i.patent_id }}" class="layui-btn">购买</a>
                        </div>
                     </li>
                 {% endfor %}
            {% endif %}
          <li class="layui-timeline-item">
            <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
            <div class="layui-timeline-content layui-text">
              <div class="layui-timeline-title">暂无更多</div>
            </div>
          </li>
        </ul>
    </body>
{% endblock %}